
#include "Const_Pub.h"
// 中间标志常量表
const tagFlagTab g_tFlagTab[]=
{
	{EN_FLAG_INIT       ,   CN_NULL_PINNO ,    {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "上电初始化"   ,    "FLAG_INIT"},
	{EN_FLAG_RESET_DI   ,   EN_DTYPE_DI ,      {EN_DI_RESET,
	                                            CN_NULL_PINNO},   CN_FLAG_EQL,   CN_NULL_PINNO,  0,  "复归信号"   ,    "FLAG_RESET_DI"},
	{EN_FLAG_RESET_GOIN ,   EN_DTYPE_GOIN ,    {EN_GOIN_RESET,
	                                            CN_NULL_PINNO},   CN_FLAG_EQL,   CN_NULL_PINNO,  0,  "GOOSE复归",    "FLAG_RESET_GOIN"},
	{EN_FLAG_RESET_DBG  ,   CN_NULL_PINNO ,    {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "调试复归",       "FLAG_RESET_DBG"},
	{EN_FLAG_RESET_COM  ,   CN_NULL_PINNO ,    {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "通信复归",	   "FLAG_RESET_COM"},
	{EN_FLAG_RESET      ,   EN_DTYPE_FLAG ,    {EN_FLAG_RESET_DI,
	                                            EN_FLAG_RESET_GOIN,
	                                            EN_FLAG_RESET_DBG,
	                                            EN_FLAG_RESET_COM,
	                                            CN_NULL_PINNO},   CN_FLAG_OR,    CN_NULL_PINNO,  0,  "装置复归",       "FLAG_RESET"},

	{EN_FLAG_ALM_COM    ,   CN_NULL_PINNO ,    {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "运行异常(其他CPU板)"   ,    "FLAG_ALM_COM"       },
	{EN_FLAG_CHK_COM    ,   CN_NULL_PINNO ,    {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "装置故障(其他CPU板)",       "FLAG_CHK_COM"       },
	{EN_FLAG_DBG_COM    ,   CN_NULL_PINNO ,    {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "装置调试(其他CPU板)",       "FLAG_DBG_COM"       },

	{EN_FLAG_ALM        ,   CN_NULL_PINNO ,    {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "运行异常"   ,    "FLAG_ALM"       },
	{EN_FLAG_CHK        ,   CN_NULL_PINNO ,    {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "装置故障",       "FLAG_CHK"       },
	{EN_FLAG_DBG        ,   CN_NULL_PINNO ,    {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "装置调试",       "FLAG_DBG"       },
	{EN_FLAG_DO_ALM     ,   EN_DTYPE_FLAG ,    {EN_FLAG_ALM,   // 装置告警
	                                            EN_FLAG_CHK,   // 装置自检
	                                            EN_FLAG_ALM_COM,
	                                            EN_FLAG_CHK_COM,
	                                            EN_FLAG_INIT,
	                                            CN_NULL_PINNO},   CN_FLAG_OR  ,  CN_NULL_PINNO,  0,  "运行异常出口"   ,    "FLAG_DO_ALM"       },
	{EN_FLAG_DO_CHK     ,   EN_DTYPE_FLAG ,    {EN_FLAG_CHK,   // 装置自检
	                                            EN_FLAG_DBG,   // 装置调试
	                                            EN_FLAG_CHK_COM,
	                                            EN_FLAG_DBG_COM,
	                                            EN_FLAG_INIT,
	                                            CN_NULL_PINNO},   CN_FLAG_OR  ,  CN_NULL_PINNO,  0,  "装置故障出口"   ,    "FLAG_DO_CHK"       },
	{EN_FLAG_LED_RUN    ,   EN_DTYPE_FLAG,     {EN_FLAG_DO_CHK,// 装置无自检
	                                            CN_NULL_PINNO},   CN_FLAG_NO  ,  CN_NULL_PINNO,  0,  "运行指示灯",     "FLAG_LED_RUN"      },
	{EN_FLAG_LED_ALM    ,   EN_DTYPE_FLAG,     {EN_FLAG_DO_ALM,// 装置告警
	                                            CN_NULL_PINNO},   CN_FLAG_EQL ,  CN_NULL_PINNO,  0,  "告警指示灯",     "FLAG_LED_ALM"},
	{EN_FLAG_PARACHG    ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "参数变化信号",   "FLAG_PARACHG"},
	{EN_FLAG_GOIN_BHBC  ,   EN_DTYPE_GOIN,     {EN_GOIN_BSHZ1, // 闭锁重合闸1
	                                           EN_GOIN_BSHZ2,  // 闭锁重合闸2
	                                           EN_GOIN_BSHZ3,  // 闭锁重合闸3
	                                           EN_GOIN_BSHZ4,  // 闭锁重合闸4
	                                           EN_GOIN_BSHZ5,  // 闭锁重合闸5
	                                           CN_NULL_PINNO},    CN_FLAG_OR  ,  CN_NULL_PINNO,  0,  "闭锁重合闸",          "FLAG_GOIN_BHBC"},
	{EN_FLAG_DI_KKJ     ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "KKJ"       ,     "FLAG_DI_KKJ"},
	{EN_FLAG_DI_STJ     ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "STJ"       ,     "FLAG_DI_STJ"},
	{EN_FLAG_DI_SHJ     ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "SHJ"       ,     "FLAG_DI_SHJ"},
	// 保护跳闸出口合并
	{EN_FLAG_BHTZ_DO    ,   EN_DTYPE_ACT,      {EN_ACT_BHTZ,
	                                            EN_ACT_BHYT,
	                                            CN_NULL_PINNO},   CN_FLAG_OR,  CN_NULL_PINNO  ,  0,  "保护跳闸出口",   "FLAG_BHTZ_DO"     },
/*****保护跳合闸保持指示灯合并--STR*******/
	// 非电量直跳
	{EN_FLAG_DI_TJF     ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,  0,  "非电量直跳指示灯",          "FLAG_DI_TJF"       },
	{EN_FLAG_BHTZ       ,   EN_DTYPE_ACT,      {EN_ACT_BHTZ,
	                                            EN_ACT_BHYT,
	                                            EN_ACT_BZTTZ,
	                                            CN_NULL_PINNO},   CN_FLAG_OR,  CN_NULL_PINNO,  0,  "保护跳闸指示灯",   "FLAG_BHTZ"     },
	{EN_FLAG_BHHZ       ,   EN_DTYPE_ACT,      {EN_ACT_BHHZ,
	                                            EN_ACT_BZTHZ,
	                                            CN_NULL_PINNO},   CN_FLAG_OR,  CN_NULL_PINNO,  0,  "保护合闸指示灯",   "FLAG_BHHZ"     },

/*****备用出口跳闸矩阵合并--STR*******/
	{EN_FLAG_DO_BHBAK1  ,   EN_DTYPE_ACT,      {EN_ACT_BHTZ,
	                                            EN_ACT_BHHZ,
	                                            EN_ACT_BHYT,
	                                            EN_ACT_CKTZ,
	                                            EN_ACT_CKHZ,
	                                            EN_ACT_BZTTZ,
	                                            EN_ACT_BZTHZ,
	                                            CN_NULL_PINNO},   CN_FLAG_MAT,  EN_PARA_MAT_OUT1,  0,  "跳闸备用1"  ,    "FLAG_DO_BHBAK1"    },
	{EN_FLAG_DO_BHBAK2  ,   EN_DTYPE_ACT,      {EN_ACT_BHTZ,
	                                            EN_ACT_BHHZ,
	                                            EN_ACT_BHYT,
	                                            EN_ACT_CKTZ,
	                                            EN_ACT_CKHZ,
	                                            EN_ACT_BZTTZ,
	                                            EN_ACT_BZTHZ,
	                                            CN_NULL_PINNO},   CN_FLAG_MAT,  EN_PARA_MAT_OUT2,  0,  "跳闸备用2"  ,    "FLAG_DO_BHBAK2"    },
	{EN_FLAG_DO_BHBAK3  ,   EN_DTYPE_ACT,      {EN_ACT_BHTZ,
	                                            EN_ACT_BHHZ,
	                                            EN_ACT_BHYT,
	                                            EN_ACT_CKTZ,
	                                            EN_ACT_CKHZ,
	                                            EN_ACT_BZTTZ,
	                                            EN_ACT_BZTHZ,
	                                            CN_NULL_PINNO},   CN_FLAG_MAT,  EN_PARA_MAT_OUT3,  0,  "跳闸备用3",      "FLAG_DO_BHBAK3"    },
	{EN_FLAG_DO_BHBAK4  ,   EN_DTYPE_ACT,      {EN_ACT_BHTZ,
	                                            EN_ACT_BHHZ,
	                                            EN_ACT_BHYT,
	                                            EN_ACT_CKTZ,
	                                            EN_ACT_CKHZ,
	                                            EN_ACT_BZTTZ,
	                                            EN_ACT_BZTHZ,
	                                            CN_NULL_PINNO},   CN_FLAG_MAT,  EN_PARA_MAT_OUT4,  0,  "跳闸备用4",      "FLAG_DO_BHBAK4"  },
	{EN_FLAG_DO_BHBAK5_0,   EN_DTYPE_ACT,      {EN_ACT_BHTZ,
	                                            EN_ACT_BHHZ,
	                                            EN_ACT_BHYT,
	                                            EN_ACT_CKTZ,
	                                            EN_ACT_CKHZ,
	                                            EN_ACT_BZTTZ,
	                                            EN_ACT_BZTHZ,
	                                            CN_NULL_PINNO},   CN_FLAG_MAT,  EN_PARA_MAT_OUT5,  0,  "跳闸备用5(常闭)","FLAG_DO_BHBAK5_0"  },
//	{EN_FLAG_DO_BHBAK5_1,   EN_DTYPE_FLAG,     {EN_FLAG_DO_BHBAK5_0,
//	                                            CN_NULL_PINNO},   CN_FLAG_NO,   CN_NULL_PINNO,     0,  "跳闸备用5(常闭)","FLAG_DO_BHBAK5_1"  },
/*****备用出口跳闸矩阵合并--END*******/

/*****备用指示灯跳闸矩阵合并--STR*******/
	{EN_FLAG_LED_BAK21  ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  EN_PARA_MAT_LED1,    0,  "备用指示灯1",       "FLAG_LED_BAK21" },
	{EN_FLAG_LED_BAK22  ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  EN_PARA_MAT_LED2,    0,  "备用指示灯2",       "FLAG_LED_BAK22" },
	{EN_FLAG_LED_BAK23  ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  EN_PARA_MAT_LED3,    0,  "备用指示灯3",       "FLAG_LED_BAK23" },
	{EN_FLAG_LED_BAK24  ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  EN_PARA_MAT_LED4,    0,  "备用指示灯4",       "FLAG_LED_BAK24" },
	{EN_FLAG_LED_BAK31  ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  EN_PARA_MAT_LED5,    0,  "备用指示灯5",       "FLAG_LED_BAK31" },
	{EN_FLAG_LED_BAK32  ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  EN_PARA_MAT_LED6,    0,  "备用指示灯6",       "FLAG_LED_BAK32" },
/*****备用指示灯跳闸矩阵合并--END*******/
	{EN_FLAG_LNK_ENA    ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,    0,  "级联切换功能投入",       "FLAG_LNK_ENA"   },
	{EN_FLAG_V_ENA      ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,    0,  "电压切换功能投入",       "FLAG_V_ENA"     },

	{EN_FLAG_V_NULL     ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,    0,  "压切无结果",       "FLAG_V_NULL"       },
	{EN_FLAG_V_BC_INIT  ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,    0,  "压切上电保持"      ,"FLAG_V_BC_INIT"    },
	{EN_FLAG_V_BC       ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,    0,  "压切保持"      ,  "FLAG_V_BC"         },
	{EN_FLAG_V_I        ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,    0,  "压切取Ⅰ母",       "FLAG_V_I"          },
	{EN_FLAG_V_II       ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,    0,  "压切取Ⅱ母",       "FLAG_V_II"         },
	{EN_FLAG_SV_A       ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,    0,  "A套数据正常",      "FLAG_SV_A"         },
	{EN_FLAG_SV_B       ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,    0,  "B套数据正常",      "FLAG_SV_B"         },
	{EN_FLAG_LNK_BC     ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,    0,  "级联保持",        "FLAG_LNK_BC"        },
	{EN_FLAG_LNK_A      ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,    0,  "级联取A套",       "FLAG_LNK_A"        },
	{EN_FLAG_LNK_B      ,   CN_NULL_PINNO,     {CN_NULL_PINNO},   CN_FLAG_NULL,  CN_NULL_PINNO,    0,  "级联取B套",       "FLAG_LNK_B"        },
};

const DWORD g_NUM_FLAG = sizeof(g_tFlagTab) / sizeof(tagFlagTab);

const tagInterTab g_tInterTab[]=
{
	{EN_INTER_SVSUB_CFG        ,   EN_CTYPE_PARA_B ,    "SV订阅配置异常总"         ,    "INTER_SVSUB_CFG"},
	{EN_INTER_SVSUB_A_CHK      ,   EN_CTYPE_PARA_B ,    "SV订阅A套异常"          ,    "INTER_SVSUB_A_CHK"},
	{EN_INTER_SVSUB_B_CHK      ,   EN_CTYPE_PARA_B ,    "SV订阅B套异常"          ,    "INTER_SVSUB_B_CHK"},
	{EN_INTER_SVSUB_NOPUB      ,   EN_CTYPE_PARA_B ,    "SV无订阅"             ,    "INTER_SVSUB_NOPUB"},
	{EN_INTER_SVSUB_PORT       ,   EN_CTYPE_PARA_B ,    "SV订阅端口配置错"         ,    "INTER_SVSUB_PORT"},
	{EN_INTER_SVSUB_NUMERR     ,   EN_CTYPE_PARA_B ,    "SV订阅控制块个数越限"         ,  "INTER_SVSUB_NUMERR"},
	{EN_INTER_SVSUB_PARAERR    ,   EN_CTYPE_PARA_B ,    "SV订阅控制块解析异常"         ,   "INTER_SVSUB_PARAERR"},
	{EN_INTER_SVSUB_ADRERR     ,   EN_CTYPE_PARA_B ,    "SV订阅控制块短地址错"         ,  "INTER_SVSUB_ADRERR"},
	{EN_INTER_SVSUB_CFGERR     ,   EN_CTYPE_PARA_B ,    "SV订阅控制块其他配置错"         ,"INTER_SVSUB_CFGERR"},
	{EN_INTER_SVSUB_1M_1LINKA  ,   EN_CTYPE_PARA_B ,    "单母线仅A套订阅"          ,    "INTER_SVSUB_1M_1LINKA"},
	{EN_INTER_SVSUB_1M_1LINKB  ,   EN_CTYPE_PARA_B ,    "单母线仅B套订阅"          ,    "INTER_SVSUB_1M_1LINKB"},
	{EN_INTER_SVSUB_1M_2LINK   ,   EN_CTYPE_PARA_B ,    "单母线双套订阅"           ,    "INTER_SVSUB_1M_2LINK"},
	{EN_INTER_SVSUB_2M_1LINKA  ,   EN_CTYPE_PARA_B ,    "双母线仅A套订阅"          ,    "INTER_SVSUB_2M_1LINKA"},
	{EN_INTER_SVSUB_2M_1LINKB  ,   EN_CTYPE_PARA_B ,    "双母线仅B套订阅"          ,    "INTER_SVSUB_2M_1LINKB"},
	{EN_INTER_SVSUB_2M_2LINK   ,   EN_CTYPE_PARA_B ,    "双母线双套订阅"           ,    "INTER_SVSUB_2M_2LINK"},
	{EN_INTER_SVSUB_A_DIS      ,   EN_CTYPE_PARA_B ,    "A套Ⅰ/Ⅱ母订阅不一致"      ,    "INTER_SVSUB_A_DIS"},
	{EN_INTER_SVSUB_A_MULT     ,   EN_CTYPE_PARA_B ,    "A套Ⅰ/Ⅱ母跨控制块订阅"    ,     "INTER_SVSUB_A_MULT"},
	{EN_INTER_SVSUB_B_DIS      ,   EN_CTYPE_PARA_B ,    "B套Ⅰ/Ⅱ母订阅不一致"      ,    "INTER_SVSUB_B_DIS"},
	{EN_INTER_SVSUB_B_MULT     ,   EN_CTYPE_PARA_B ,    "B套Ⅰ/Ⅱ母跨控制块订阅"    ,     "INTER_SVSUB_B_MULT"},
	{EN_INTER_SVSUB_1M_DIS     ,   EN_CTYPE_PARA_B ,    "Ⅰ母A/B套订阅不一致"       ,    "INTER_SVSUB_1M_DIS"},
	{EN_INTER_SVSUB_2M_DIS     ,   EN_CTYPE_PARA_B ,    "Ⅱ母A/B套订阅不一致"      ,    "INTER_SVSUB_2M_DIS"},
	{EN_INTER_SVSUB_A1_VALID   ,   EN_CTYPE_PARA_B ,    "A套Ⅰ母电压订阅有效"       ,     "INTER_SVSUB_A1_VALID"},
	{EN_INTER_SVSUB_A1_CFG     ,   EN_CTYPE_PARA_B ,    "A套Ⅰ母电压有订阅"         ,    "INTER_SVSUB_A1_CFG"},
	{EN_INTER_SVSUB_A1_LOSE    ,   EN_CTYPE_PARA_B ,    "A套Ⅰ母电压未全订阅"       ,     "INTER_SVSUB_A1_LOSE"},
	{EN_INTER_SVSUB_A1_MULT    ,   EN_CTYPE_PARA_B ,    "A套Ⅰ母电压跨控制块订阅"   ,    "INTER_SVSUB_A1_MULT"},
	{EN_INTER_SVSUB_A2_VALID   ,   EN_CTYPE_PARA_B ,    "A套Ⅱ母电压订阅有效"      ,     "INTER_SVSUB_A2_VALID"},
	{EN_INTER_SVSUB_A2_CFG     ,   EN_CTYPE_PARA_B ,    "A套Ⅱ母电压有订阅"        ,    "INTER_SVSUB_A2_CFG"},
	{EN_INTER_SVSUB_A2_LOSE    ,   EN_CTYPE_PARA_B ,    "A套Ⅱ母电压未全订阅"      ,     "INTER_SVSUB_A2_LOSE"},
	{EN_INTER_SVSUB_A2_MULT    ,   EN_CTYPE_PARA_B ,    "A套Ⅱ母电压跨控制块订阅"  ,    "INTER_SVSUB_A2_MULT"},
	{EN_INTER_SVSUB_B1_VALID   ,   EN_CTYPE_PARA_B ,    "B套Ⅰ母电压订阅有效"       ,      "INTER_SVSUB_B1_VALID"},
	{EN_INTER_SVSUB_B1_CFG     ,   EN_CTYPE_PARA_B ,    "B套Ⅰ母电压有订阅"         ,     "INTER_SVSUB_B1_CFG"},
	{EN_INTER_SVSUB_B1_LOSE    ,   EN_CTYPE_PARA_B ,    "B套Ⅰ母电压未全订阅"       ,      "INTER_SVSUB_B1_LOSE"},
	{EN_INTER_SVSUB_B1_MULT    ,   EN_CTYPE_PARA_B ,    "B套Ⅰ母电压跨控制块订阅"   ,    "INTER_SVSUB_B1_MULT"},
	{EN_INTER_SVSUB_B2_VALID   ,   EN_CTYPE_PARA_B ,    "B套Ⅱ母电压订阅有效"      ,     "INTER_SVSUB_B2_VALID"},
	{EN_INTER_SVSUB_B2_CFG     ,   EN_CTYPE_PARA_B ,    "B套Ⅱ母电压有订阅"       ,    "INTER_SVSUB_B2_CFG"},
	{EN_INTER_SVSUB_B2_LOSE    ,   EN_CTYPE_PARA_B ,    "B套Ⅱ母电压未全订阅"      ,     "INTER_SVSUB_B2_LOSE"},
	{EN_INTER_SVSUB_B2_MULT    ,   EN_CTYPE_PARA_B ,    "B套Ⅱ母电压跨控制块订阅"  ,    "INTER_SVSUB_B2_MULT"},
	{EN_INTER_SVPUB_CFG        ,   EN_CTYPE_PARA_B ,    "SV发布配置异常总"      ,        "INTER_SVPUB_CFG"},
	{EN_INTER_SVPUB_PORT       ,   EN_CTYPE_PARA_B ,    "SV发布端口配置错"     ,         "INTER_SVPUB_PORT"},
	{EN_INTER_SVPUB_NUMERR     ,   EN_CTYPE_PARA_B ,    "SV发布控制块个数越限"         ,   "INTER_SVPUB_NUMERR"},
	{EN_INTER_SVPUB_PARAERR    ,   EN_CTYPE_PARA_B ,    "SV发布控制块解析异常"         ,   "INTER_SVPUB_PARAERR"},
	{EN_INTER_SVPUB_ADRERR     ,   EN_CTYPE_PARA_B ,    "SV发布控制块短地址错"         ,   "INTER_SVPUB_ADRERR"},
	{EN_INTER_SVPUB_CFGERR     ,   EN_CTYPE_PARA_B ,    "SV发布控制块其他配置错"         ,  "INTER_SVPUB_CFGERR"},
	{EN_INTER_SVPUB_CHN_NUM    ,   EN_CTYPE_PARA_B ,    "SV发布通道数越限"       ,       "INTER_SVPUB_CHN_NUM"},
	{EN_INTER_SVPUB_CHN_NO     ,   EN_CTYPE_PARA_B ,    "SV发布通道号越限",              "INTER_SVPUB_CHN_NO"},
	{EN_INTER_SVPUB_DLY        ,   EN_CTYPE_PARA_B ,    "SV发布缺少通道延时",             "INTER_SVPUB_DLY"},
	{EN_INTER_SVPUB_SUB        ,   EN_CTYPE_PARA_B ,	"SV发布有级联通道",              "INTER_SVPUB_SUB"},
	{EN_INTER_SVPUB_STD        ,   EN_CTYPE_PARA_B ,    "标准SV(母线电压级联)发布",    "INTER_SVPUB_STD"},
	{EN_INTER_SVPUB_ANA        ,   EN_CTYPE_PARA_B ,    "标准SV(母线电压直采)发布",    "INTER_SVPUB_ANA"},
	{EN_INTER_SVPUB_M          ,   EN_CTYPE_PARA_B ,    "标准SV(母线板无电压配置)发布", "INTER_SVPUB_M"},
	{EN_INTER_SVPUB_CHK        ,   EN_CTYPE_PARA_B ,    "非标准SV发布"               ,  "INTER_SVPUB_CHK"},
	{EN_INTER_GOSUB_CFG        ,   EN_CTYPE_PARA_B ,    "GOOSE订阅配置异常总"          , "INTER_GOSUB_CFG"},
	{EN_INTER_GOSUB_PORT       ,   EN_CTYPE_PARA_B ,    "GOOSE订阅端口配置错"          , "INTER_GOSUB_PORT"},
	{EN_INTER_GOSUB_NUMERR     ,   EN_CTYPE_PARA_B ,    "GOOSE订阅控制块个数越限"         ,   "INTER_GOSUB_NUMERR"},
	{EN_INTER_GOSUB_PARAERR    ,   EN_CTYPE_PARA_B ,    "GOOSE订阅控制块解析异常"         ,   "INTER_GOSUB_PARAERR"},
	{EN_INTER_GOSUB_ADRERR     ,   EN_CTYPE_PARA_B ,    "GOOSE订阅控制块短地址错"         ,   "INTER_GOSUB_ADRERR"},
	{EN_INTER_GOSUB_CFGERR     ,   EN_CTYPE_PARA_B ,    "GOOSE订阅控制块其他配置错"         ,    "INTER_GOSUB_CFGERR"},
	{EN_INTER_GOSUB_Dif        ,   EN_CTYPE_PARA_B ,    "GOOSE订阅不一致"                , "INTER_GOSUB_Dif"},
	{EN_INTER_GOSUB_GOCB       ,   EN_CTYPE_PARA_B ,    "GOOSE订阅控制块错误"              , "INTER_GOSUB_GOCB"},
	{EN_INTER_GOSUB_V          ,   EN_CTYPE_PARA_B ,    "GOOSE数据有订阅"                , "INTER_GOSUB_V"},
	{EN_INTER_GOSUB_T          ,   EN_CTYPE_PARA_B ,    "GOOSE时标有订阅"                , "INTER_GOSUB_T"},
	{EN_INTER_GOSUB_Q          ,   EN_CTYPE_PARA_B ,    "GOOSE品质有订阅"                , "INTER_GOSUB_Q"},

	{EN_INTER_GOPUB_CFG        ,   EN_CTYPE_PARA_B ,    "GOOSE发布配置异常总"              , "INTER_GOPUB_CFG"},
	{EN_INTER_GOPUB_PORT       ,   EN_CTYPE_PARA_B ,    "GOOSE发布端口配置错"              , "INTER_GOPUB_PORT"},
	{EN_INTER_GOPUB_NUMERR     ,   EN_CTYPE_PARA_B ,    "GOOSE发布控制块个数越限"            , "INTER_GOPUB_NUMERR"},
	{EN_INTER_GOPUB_PARAERR    ,   EN_CTYPE_PARA_B ,    "GOOSE发布控制块解析异常"            , "INTER_GOPUB_PARAERR"},
	{EN_INTER_GOPUB_ADRERR     ,   EN_CTYPE_PARA_B ,    "GOOSE发布控制块短地址错"            , "INTER_GOPUB_ADRERR"},
	{EN_INTER_GOPUB_CFGERR     ,   EN_CTYPE_PARA_B ,    "GOOSE发布控制块其他配置错"           , "INTER_GOPUB_CFGERR"},
	{EN_INTER_GOPUB_DI_LOSE    ,   EN_CTYPE_PARA_B ,    "单点硬遥信未全发布"                 , "INTER_GOPUB_DI_LOSE"},
	{EN_INTER_GOPUB_DI_T       ,   EN_CTYPE_PARA_B ,    "单点硬遥信时标未全发布"               , "INTER_GOPUB_DI_T"},
	{EN_INTER_GOPUB_DI_Q       ,   EN_CTYPE_PARA_B ,    "单点硬遥信有品质发布"                , "INTER_GOPUB_DI_Q"},
	{EN_INTER_GOPUB_DI_Dif     ,   EN_CTYPE_PARA_B ,    "单点硬遥信发布不一致"                , "INTER_GOPUB_DI_Dif"},
	{EN_INTER_GOPUB_DPI_LOSE   ,   EN_CTYPE_PARA_B ,    "双点硬遥信未全发布"                 , "INTER_GOPUB_DPI_LOSE"},
	{EN_INTER_GOPUB_DPI_T      ,   EN_CTYPE_PARA_B ,    "双点硬遥信时标未全发布"               , "INTER_GOPUB_DPI_T"},
	{EN_INTER_GOPUB_DPI_Q      ,   EN_CTYPE_PARA_B ,    "双点硬遥信有品质发布"                , "INTER_GOPUB_DPI_Q"},
	{EN_INTER_GOPUB_DPI_Dif    ,   EN_CTYPE_PARA_B ,    "双点硬遥信发布不一致"                , "INTER_GOPUB_DPI_Dif"},
	{EN_INTER_GOPUB_OUT_LOSE   ,   EN_CTYPE_PARA_B ,    "虚遥信未全发布"                   , "INTER_GOPUB_OUT_LOSE"},
	{EN_INTER_GOPUB_OUT_Q      ,   EN_CTYPE_PARA_B ,    "虚遥信有品质发布"                  , "INTER_GOPUB_OUT_Q"},
	{EN_INTER_GOPUB_OUT_Dif    ,   EN_CTYPE_PARA_B ,    "虚遥信发布不一致"                  , "INTER_GOPUB_OUT_Dif"},
	{EN_INTER_GOPUB_DC_LOSE    ,   EN_CTYPE_PARA_B ,    "直流未全发布"                    , "INTER_GOPUB_DC_LOSE"},
	{EN_INTER_GOPUB_DC_Q       ,   EN_CTYPE_PARA_B ,    "直流有品质发布"                   , "INTER_GOPUB_DC_Q"},
	{EN_INTER_GOPUB_DC_Dif     ,   EN_CTYPE_PARA_B ,    "直流发布不一致"                   , "INTER_GOPUB_DC_Dif"},
	{EN_INTER_RUN_SV_BS        ,   EN_CTYPE_PARA_B,     "SV发布闭锁"                    , "INTER_RUN_SV_BS"},
	{EN_INTER_RUN_SV_ENA       ,   EN_CTYPE_PARA_B,     "SV发布使能"                    , "INTER_RUN_SV_ENA"},
	{EN_INTER_RUN_SV_ENA_ELSE  ,   EN_CTYPE_PARA_B,     "SV发布使能过"                   , "INTER_RUN_SV_ENA_ELSE"},
	{EN_INTER_RUN_GO_BS        ,   EN_CTYPE_PARA_B,     "GOOSE发布闭锁"                 , "INTER_RUN_GO_BS"},
	{EN_INTER_RUN_GO_ENA       ,   EN_CTYPE_PARA_B,     "GOOSE发布使能"                 , "INTER_RUN_GO_ENA"},
	{EN_INTER_RUN_GO_ENA_ELSE  ,   EN_CTYPE_PARA_B,     "GOOSE发布使能过"                , "INTER_RUN_GO_ENA_ELSE"},
	{EN_INTER_OPT_ANA          ,   EN_CTYPE_PARA_B,     "积分幅值查看"                    , "INTER_OPT_ANA"},
	{EN_INTER_OPT_ANA_J        ,   EN_CTYPE_PARA_B,     "基波幅值查看"                    , "INTER_OPT_ANA_J"},
	{EN_INTER_OPT_ANA_HUM      ,   EN_CTYPE_PARA_B,     "谐波查看"                      , "INTER_OPT_ANA_HUM"},
	{EN_INTER_OPT_ANA_FR       ,   EN_CTYPE_PARA_B,     "频率查看"                      , "INTER_OPT_ANA_FR"},
	{EN_INTER_POW_LOS          ,   EN_CTYPE_PARA_B,     "装置掉电(瞬时)"                  , "INTER_POW_LOS"},
	{EN_INTER_POW_LOS_RLY      ,   EN_CTYPE_PARA_B,     "装置掉电(去颤后)"                , "INTER_POW_LOS_RLY"},
	{EN_INTER_POW_LOS_EVT      ,   EN_CTYPE_PARA_B,     "装置掉电已记录"                  , "INTER_POW_LOS_EVT"},
	{EN_INTER_CPU2_CTRL        ,   EN_CTYPE_PARA_B,     "CPU2接管标志"                  , "INTER_CPU2_CTRL"},
	{EN_INTER_CPU2_CTRL_ZK     ,   EN_CTYPE_PARA_B,     "CPU2非接管释放直控权限"             , "INTER_CPU2_CTRL_ZK"},
	{EN_INTER_CPU2_CTRL_DBG    ,   EN_CTYPE_PARA_B,     "直控出口调试状态"                , "INTER_CPU2_CTRL_DBG"},
	{EN_INTER_LCD_VIR          ,   EN_CTYPE_PARA_B,     "虚拟LCD通信断开"                 , "INTER_LCD_VIR"},

};
const DWORD g_NUM_INTER = sizeof(g_tInterTab) / sizeof(tagInterTab);


